Pensionbee_Data_Model:
  target: ci
  outputs:

    ci:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: PB_DEVELOPER
      warehouse: COMPUTE_WH_MEDIUM
      database: PENSIONBEE_ANALYTICS
      schema: dbt_ci
      threads: 12
